# Generated by Django 4.1.7 on 2023-03-16 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phonenumber",
            field=models.TextField(default=None, unique=True),
        ),
    ]
