# Generated by Django 4.1.7 on 2023-03-07 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("joonggo", "0006_comment_modify_date_sell_modify_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="sell",
            name="voter",
            field=models.ManyToManyField(
                related_name="voter_sell", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="sell",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author_sell",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
