# Generated by Django 4.1.7 on 2023-03-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("joonggo", "0007_sell_voter_alter_sell_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="sell",
            name="price",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
