# Generated by Django 4.1.7 on 2023-03-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("joonggo", "0008_sell_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sell",
            name="price",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
