# Generated by Django 4.1.7 on 2023-03-14 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("joonggo", "0009_alter_sell_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img_root", models.FileField(upload_to="Uploaded Files/imgs")),
                ("img_uploaddate", models.DateField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="sell",
            name="price",
        ),
    ]
