# Generated by Django 4.1.7 on 2023-03-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("joonggo", "0010_image_remove_sell_price"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Image",
        ),
        migrations.AddField(
            model_name="sell",
            name="category",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="sell",
            name="images",
            field=models.ImageField(blank=True, upload_to="images"),
        ),
        migrations.AddField(
            model_name="sell",
            name="price",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sell",
            name="tmethod",
            field=models.TextField(default=""),
        ),
    ]
