# Generated by Django 4.1.7 on 2023-03-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("joonggo", "0011_delete_image_sell_category_sell_images_sell_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sell",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sell",
            name="subject",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
